package com.cmpe172.irated.rest.model;

import java.io.Serializable;

import java.text.SimpleDateFormat;
import java.util.Calendar;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "rating")
public class Rating implements Serializable{
    private static final long serialVersionUID = 1L;

    Calendar cal = Calendar.getInstance();
    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");

    private String ratingId;
    private String firstName;
    private String lastName;
    private String college;
    private String department;
    private String content;
    private String timestamp = sdf.format(cal.getTime());

    @DynamoDBHashKey(attributeName = "ratingId")
    @DynamoDBAutoGeneratedKey
    public String getRatingId(){
        return ratingId;
    }

    public void setRatingId(String ratingId){
        this.ratingId = ratingId;
    }

    @DynamoDBAttribute
    public String getFirstName(){
        return firstName;
    }

    public void setFirstName(String firstName){
        this.firstName = firstName;
    }

    @DynamoDBRangeKey
    public String getLastName(){
        return lastName;
    }

    public void setLastName(String lastName){
        this.lastName = lastName;
    }

    @DynamoDBAttribute
    public String getCollege(){
        return college;
    }

    public void setCollege(String college){
        this.college = college;
    }

    @DynamoDBAttribute
    public String getDepartment(){
        return department;
    }

    public void setDepartment(String department){
        this.department = department;
    }

    @DynamoDBAttribute
    public String getContent(){
        return content;
    }

    public void setContent(String content){
        this.content = content;
    }

    @DynamoDBAttribute
    public String getTimestamp(){
        return timestamp;
    }
}